FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /src/web-server ./cmd/web

FROM alpine:latest
WORKDIR /app
COPY --from=builder /src/web .
COPY --from=builder /src/web-server .
CMD ["/app/web-server"]