FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /src/sin-api ./cmd/sinapi

FROM alpine:latest
COPY --from=builder /src/sin-api /app/sin-api
CMD ["/app/sin-api"]